### ISSUE TITLE
Error after installing vuels or tailwindcssls

### ISSUE THREAD

**Issue by danymat** [MordechaiHadad/nvim-lspmanager#21]
```
Successfully installed vuels
Error executing vim.schedule lua callback: ...ite/pack/packer/start/nvim-lspmanager/lua/lspmanager.lua:57: attempt to index a nil value
```

**Comment by MordechaiHadad** [comment]
> 
> 
> ```
> Successfully installed vuels
> Error executing vim.schedule lua callback: ...ite/pack/packer/start/nvim-lspmanager/lua/lspmanager.lua:57: attempt to index a nil value
> ```

Please provide more details.

**Comment by danymat** [comment]
The error seems to have resolved somehow. I close this issue.
